name: poker-with-friends-dev

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: poker
      POSTGRES_PASSWORD: poker
      POSTGRES_DB: poker
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - poker-dev-postgres:/var/lib/postgresql
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U poker -d poker']
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  poker-dev-postgres:
